# fly.toml app configuration file generated for smart-brain-api-fly on 2023-05-17T12:47:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smart-brain-api-fly"
primary_region = "otp"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
